### ISSUE TITLE
Some rooms (for example, room 16) are not loading because of nil tile values, it doesn't look like actual tiles are missing in the room grid though

### ISSUE THREAD

**Issue by themost1** [ile123ile/HermanElectro#5]
The problem is fixed if you check if room[i+1][j] is nil in line 231 of main.lua, but we should probably figure out why this is actually happening.

**Comment by ile123ile** [comment]
I could not reproduce this bug at all. Are you running into them randomly or loading them with the roomHack?

**Comment by ile123ile** [comment]
Also, tiles are nil when there's nothing on them, the id is 0 and the tile is nil

**Comment by themost1** [comment]
The problem seems fixed after the most recent push. For the record, I only experienced it before through the roomHack.
